spring:
  application:
    name: DemoVirtualThreads
  threads:
    virtual:
      enabled: true
      manually: false
server:
  port: 8080
  servlet:
    context-path: /DemoVirtualThreads
  tomcat.max-connections: 200
  tomcat.max-threads: 200
#logging.level.org.springframework.web.reactive: DEBUG
#logging.level.reactor.netty: DEBUG

provider:
  service:
    rx.url: http://localhost:8081/producer/api/sensors/rx
    webflux.url: http://localhost:8081/producer/api/sensors/webflux
